version: '3.7'

services:
  php-httpd:
    build:
      context: dockerExternal/php-dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.2
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "Europe/Berlin"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_DATABASE: 'dev'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-volume: