version: '3'
services:
  webserver:
    image: phpstorm/php-apache:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
